package com.kuraiji.speedyplaylistcreator.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF8F4E00)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDCC2)
val light_onPrimaryContainer = Color(0xFF2E1500)
val light_secondary = Color(0xFF745943)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFFFDCC2)
val light_onSecondaryContainer = Color(0xFF2A1707)
val light_tertiary = Color(0xFF5B6237)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFE0E7B1)
val light_onTertiaryContainer = Color(0xFF191E00)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF201B17)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF201B17)
val light_surfaceVariant = Color(0xFFF3DFD1)
val light_onSurfaceVariant = Color(0xFF51443B)
val light_outline = Color(0xFF847469)
val light_inverseOnSurface = Color(0xFFFAEEE8)
val light_inverseSurface = Color(0xFF352F2B)
val light_inversePrimary = Color(0xFFFFB77A)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF8F4E00)
val light_surfaceTintColor = Color(0xFF8F4E00)

val dark_primary = Color(0xFFFFB77A)
val dark_onPrimary = Color(0xFF4C2700)
val dark_primaryContainer = Color(0xFF6D3A00)
val dark_onPrimaryContainer = Color(0xFFFFDCC2)
val dark_secondary = Color(0xFFE3C0A5)
val dark_onSecondary = Color(0xFF412C19)
val dark_secondaryContainer = Color(0xFF5A422E)
val dark_onSecondaryContainer = Color(0xFFFFDCC2)
val dark_tertiary = Color(0xFFC4CB97)
val dark_onTertiary = Color(0xFF2D330D)
val dark_tertiaryContainer = Color(0xFF444A22)
val dark_onTertiaryContainer = Color(0xFFE0E7B1)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF201B17)
val dark_onBackground = Color(0xFFECE0DA)
val dark_surface = Color(0xFF201B17)
val dark_onSurface = Color(0xFFECE0DA)
val dark_surfaceVariant = Color(0xFF51443B)
val dark_onSurfaceVariant = Color(0xFFD6C3B6)
val dark_outline = Color(0xFF9E8E82)
val dark_inverseOnSurface = Color(0xFF201B17)
val dark_inverseSurface = Color(0xFFECE0DA)
val dark_inversePrimary = Color(0xFF8F4E00)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFFFFB77A)
val dark_surfaceTintColor = Color(0xFFFFB77A)


val seed = Color(0xFFFF8F00)